### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by mytototo** [continuous-software/42-cent#2]
Hey!

I just discovered  42-cent. It appears the 42-cent repos are not active anymore. Is the project still maintained? Is is reliable and stable for production?

Thanks.

**Comment by maxinnos** [comment]
Hi mytototo,

The repo hasn't been updated in a while as you can see. It has been in use for stable production applications though.

Thanks

**Comment by mytototo** [comment]
Thanks for your answer @maxinnos. You should at least update your dependencies so developers can see it's a reliable product.

**Comment by kytwb** [comment]
@mytototo added a badge to show that our dependencies are up-to-date.
